#! python3
# password_locker.py - An insecure password locker program
#modules:
import sys, pyperclip

#dictionary:
PASSWORDS = {'email': 'F7minlBDDuvMJuxESSKHFhTxFtjVB6',
             'blog': 'VmALvQyKAxiVH5G8v01if1MLZF3sdt',
             'luggage': '12345'}
			 
#begin code
if len(sys.argv) < 2:
    print('''Usage: "password_locker account" - copy account password''') #Error message if an account is not provided as an argument
    sys.exit()

account = sys.argv[1]      # first command line arg is the account name

print('Looking for ' + account + ' in passwords')
if account in PASSWORDS:
	pyperclip.copy(PASSWORDS[account])
	print('Password for ' + account + ' copied to clipboard.')
else:
    print('There is no account named ' + account)
#end code
